# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Project validation ✅

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  adi-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Switch to working directory
      run: cd adi-back

    - name: Build
      run: go build -v ./adi-back/...

    - name: Test
      run: go test -v ./adi-back/...

  adi-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Switch to working directory
      run: cd adi-front

    - name: Installing dependencies
      run: npm ci

    - name: Build
      run: npm run build

  adi-front-design-system:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Switch to working directory
      run: cd adi-front-design-system

    - name: Installing dependencies
      run: npm ci

    - name: Build
      run: npm run build
